### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by Yafine** [glazec/hexo-web-push-notification#1]

**Comment by Yafine** [comment]
> 获取不到文章的summary属性值

**Comment by glazec** [comment]
解决了？

**Comment by Yafine** [comment]
> 解决了？

解决了，那个文章通知的样式再哪设置啊？

**Comment by glazec** [comment]
在Webpushr的网站上进行更改

**Comment by glazec** [comment]
![image](https://user-images.githubusercontent.com/22890026/77862821-d93dd380-71d2-11ea-8e8c-5c45cfdd9a54.png)
