### ISSUE TITLE
nvalid json response

### ISSUE THREAD

**Issue by Uzizkp** [glazec/hexo-web-push-notification#10]
<img width="1103" alt="截屏2020-07-15 10 02 08" src="https://user-images.githubusercontent.com/41053750/87519922-8fde9a80-c682-11ea-91a8-a027c9905aca.png">

**Comment by glazec** [comment]
请问您插件的版本是最新版吗？

**Comment by Uzizkp** [comment]
> 请问您插件的版本是最新版吗？

是的,本来可以用的,但是我换了一下blog的仓库好像路径出了问题

**Comment by glazec** [comment]
看起来是newPost.json解析错误。你尝试把public/newPost.json删除。然后再generate，deploy尝试。

**Comment by glazec** [comment]
https://zkpeace.com/newPost.json也要删除
