### ISSUE TITLE
Set up to not request push notification permission on page load

### ISSUE THREAD

**Issue by tienhm0202** [glazec/hexo-web-push-notification#11]
![Imgur](https://i.imgur.com/1E6D2Zn.png)

How can I set up when to ask push notification permission (after 30s for example). Because it make Google score lower

**Comment by glazec** [comment]
I think we can execute the notification script sometimes after page load, but I am not sure how to do it. Do you have any ideas?

**Comment by tienhm0202** [comment]
> I think we can execute the notification script sometimes after page load, but I am not sure how to do it. Do you have any ideas?

I think we can execute the notification script after triggers like: `after page load 30s` or `scrolled 1/3 view`.

**Comment by glazec** [comment]
Scrolling 1/3 view would be a great idea, since scrolling shows visitors' interests. Would you like to have a try and open a PR?

**Comment by glazec** [comment]
9af5d42

**Comment by tienhm0202** [comment]
Thank you @glazec. I'm going to close this issue.

**Comment by tienhm0202** [comment]
![](https://i.imgur.com/DJ5LS1N.png)

Now, Webpushr has updated this feature into their system, supported both scrolled view point and delayed seconds

**Comment by glazec** [comment]
That's awesome. I will roll back the main branch
