### ISSUE TITLE
请求更新相关依赖

### ISSUE THREAD

**Issue by CCKNBC** [glazec/hexo-web-push-notification#14]
![-2020-11-29-123439.png](https://img.maocdn.cn/img/2020/11/29/-2020-11-29-123439.png)

[https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md](https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md)
https://github.com/highlightjs/highlight.js/issues/2877

**Comment by glazec** [comment]
已更新

**Comment by CCKNBC** [comment]
> 已更新，谢谢提醒。

感谢开发，又可以愉快使用了
