### ISSUE TITLE
webpushr 代码变更还是我配置错误

### ISSUE THREAD

**Issue by o1f** [glazec/hexo-web-push-notification#17]
文档![](https://cdn.uzz5.com/tmp/zY2uwt2v07.png)

webpushr![](https://cdn.uzz5.com/tmp/r1PoXJ1MAt.png)

手动更改之后网站才会显示

**Comment by glazec** [comment]
更新了。发布了v0.3.2

**Comment by o1f** [comment]
![](https://cdn.uzz5.com/tmp/X5WLp6buPy.png)emm,这里应该在这吧.

更新插件之后

部署提示 Plugin load failed: %s hexo-web-push-notification

**Comment by glazec** [comment]
你再试试？最新的是4.0

**Comment by o1f** [comment]
好家伙 ,这迭代起飞了..

**Comment by glazec** [comment]
我git,npm用的烂。懒得弄，直接往上堆就是

**Comment by o1f** [comment]
已无报错,感谢大佬~

**Comment by o1f** [comment]
https://github.com/glazec/hexo-web-push-notification/issues/8

修改了之后好像好了
![](https://cdn.uzz5.com/tmp/G0pF7YgwLC.png)
-------

~~大佬 又有问题了~~
~~这是我新建文章测试的~~
![](https://cdn.uzz5.com/tmp/trKttkh3wh.png)
~~查看 newPost.json 文件已变更了~~

~~我是利用git部署在国内服务器上的,是不是太快了~~
