### ISSUE TITLE
同步新文章的时候报错

### ISSUE THREAD

**Issue by Uzizkp** [glazec/hexo-web-push-notification#2]
`` ERROR Push Notification failed {"status":"failure","type":"missing_parameter","description":"Missing required parameter 'message'"} ``

**Comment by glazec** [comment]
看起来是调用webpushr api的时候少了message这个参数

**Comment by Uzizkp** [comment]
> 看起来是调用webpushr api的时候少了message这个参数

大佬知道在哪里添加吗？我是个菜鸡

**Comment by glazec** [comment]
可以把你更新的博客markdown源码贴出来么

**Comment by Uzizkp** [comment]
> 可以把你更新的博客markdown源码贴出来么
title: 认知机器人：感知物体位置和形态
date: 2020-04-16 21:24:54
tags:
    - 项目
    - Ros
    - 机器人
category:
    - 项目
cover: https://img-1253324855.cos.ap-chengdu.myqcloud.com/myweb/articles/cg_lab/cover.png
---

## 内容略

**Comment by glazec** [comment]
原因应该是你没有为文章设置excerpt。可以再展示一下你的newPost.json么

**Comment by Uzizkp** [comment]
> 原因应该是你没有为文章设置excerpt。可以再展示一下你的newPost.json么

可以的

`{"title":"认知机器人：感知物体位置和形态","id":"2020/04/16/认知机器人：感知物体位置和状态/","date_published":"04/16/2020","summary":"","url":"https://zkpeace.com/2020/04/16/%E8%AE%A4%E7%9F%A5%E6%9C%BA%E5%99%A8%E4%BA%BA%EF%BC%9A%E6%84%9F%E7%9F%A5%E7%89%A9%E4%BD%93%E4%BD%8D%E7%BD%AE%E5%92%8C%E7%8A%B6%E6%80%81/","tags":["项目","Ros","机器人"],"categories":["项目"]}`

**Comment by glazec** [comment]
希望你能为你的文章添加上excerpt，然后在重新试一下。Excerpt样例：
```
---
title: Hexo使用Web Push Notification 浏览器通知推送
tags:
  - hexo
  - 服务器推送技术
  - push notifications
categories:
  - 开发
comments: true
abbrlink: 98ae9e55
date: 2020-02-26 10:00:00
---

Web Push Notification 是怎么工作的？个人博客为什么要使用它？如何使用它？

<!-- more -->
```
其中`---`和`<!-- more -->`之间的便是excerpt。

**Comment by Uzizkp** [comment]
> 希望你能为你的文章添加上excerpt，然后在重新试一下。Excerpt样例：
> 
> ```
> ---
> title: Hexo使用Web Push Notification 浏览器通知推送
> tags:
>   - hexo
>   - 服务器推送技术
>   - push notifications
> categories:
>   - 开发
> comments: true
> abbrlink: 98ae9e55
> date: 2020-02-26 10:00:00
> ---
> 
> Web Push Notification 是怎么工作的？个人博客为什么要使用它？如何使用它？
> 
> 
> ```
> 
> 其中`---`和`<!-- more -->`之间的便是excerpt。

感谢，安装了hexo-excerpt就成功了
