### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by CCKNBC** [glazec/hexo-web-push-notification#20]
因为还使用了 workbox 配合 snackbar 实现更新通知，能否每次文件变动后 webpushr-sw.js 不再重新生成，只重新生成 newPost.json ，避免我 gulp 后自己添加其他内容被覆盖
另外使用 Actions 是否也能配置环境变量 因为仓库开源 公开几个参数毕竟不太好
https://www.webpushr.com/api-playground 如果有人闲得慌，直接这样就能发送通知了
还有就是 updated 参数的可选性，虽然知道以 date 和 id 来说能判断文章上新了，文章更新通知没有必要，但是更新日期也可以纳入比较范围

**Comment by glazec** [comment]
首先关于webpusr-sw.js重新生成的问题。当初这样设计的原因是为了方便用户。因为除了在souce文件夹下放置一个webpushr-sw.js，public/webpus-sw.js在每次清空cache，重新生成后都会消失。具体如何实现webpushr-sw.js 不重新生成，我们可以再看看。

关于Action，不知道你的意思是不是将 Hexo 托管在 Github 上，用 Action 进行构建的情况下，希望 webpushr 的参数可以读取系统环境变量。

关于第三点，你的意思是希望可以更改已发布的文章后，推送更新通知？

**Comment by CCKNBC** [comment]
好的，谢谢回复

**Comment by liaochenlanruo** [comment]
> 关于第三点，你的意思是希望可以更改已发布的文章后，推送更新通知？

更新通知很有必要，希望可以开发一下，谢谢！

**Comment by glazec** [comment]
你们有兴趣提个更新通知的pr么？ @liaochenlanruo @CCKNBC

**Comment by liaochenlanruo** [comment]
> 你们有兴趣提个更新通知的pr么？ @liaochenlanruo @CCKNBC

我只是会用，却不会开发

**Comment by adaLucky** [comment]
提交新文件后，newPost 文件未发生变化，这是一个BUG吗？还是我配置错误，最后等了10多分钟依旧未收到订阅推送，通过webpushr官网手动推送是可以的
![49DBDDBE-4F77-45CA-BAF1-E4FB335AEC5D](https://user-images.githubusercontent.com/49558910/128613608-e1f35aac-2bbb-49d6-8e46-74e2b1be6aa7.png)

**Comment by glazec** [comment]
newPost的判断机制是文件创建时间。它只会采用最新创建的文件。

**Comment by adaLucky** [comment]
非常感谢能收到你的回复，经过这两天的资料查看 我在本机已经能正常运转起来了&nbsp; 不知道你是哪个国家的开发者 在中国境内如果使用 chrome 浏览器是无法进行订阅的 因为中国的网络是无法连接到 google 的订阅服务器 也就是我在网上了解到的 FCM 如果能通过一些程序访问到Google 那么通过 Chrome订阅是正常的&nbsp; 另外如果通过 微软的Edge或者 Firefox 浏览器是可以完全正常使用的&nbsp; 请问我在中国想要实现 通过chrome如何实现直接订阅&nbsp; 有能解决的方案给与帮助吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [glazec/hexo-web-push-notification] 一个小建议 (#20)






新邮局新邮局它只会采用最新创建的文件。

—
你收到这个是因为你评论了。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.
