### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by Yafine** [glazec/hexo-web-push-notification#3]
这个生成的newpost.json中有一个summary值，这个值获取的是md文章中所定义的front-mater中summary的值的内容吗？
如果不是summary，需要修改主题文件使其修改为summary吧

**Comment by glazec** [comment]
Excerpt样例：
```
---
title: Hexo使用Web Push Notification 浏览器通知推送
tags:
  - hexo
  - 服务器推送技术
  - push notifications
categories:
  - 开发
comments: true
abbrlink: 98ae9e55
date: 2020-02-26 10:00:00
---

Web Push Notification 是怎么工作的？个人博客为什么要使用它？如何使用它？

<!-- more -->
```
其中`---`和`<!-- more -->`之间的便是excerpt。

_Originally posted by @glazec in https://github.com/glazec/hexo-web-push-notification/issues/2#issuecomment-615454346_

**Comment by Yafine** [comment]
您好，这个去官网注册是他让下载的一个webpush-sw.js是需要放在站点根目录下吗

**Comment by glazec** [comment]
不用
