### ISSUE TITLE
有的浏览器显示，有的不显示

### ISSUE THREAD

**Issue by qingchenmowang** [glazec/hexo-web-push-notification#4]
我做好之后测试了下，360极速浏览器显示，谷歌不显示，我打开了允许通知，
还有就是订阅后取消不了，显示Error. Try later.
![image](https://user-images.githubusercontent.com/56811087/80333813-e1e10280-8881-11ea-9635-1a05779f2142.png)
这里测试也是没有问题

![image](https://user-images.githubusercontent.com/56811087/80333913-35535080-8882-11ea-9e75-5e615d94aa06.png)

**Comment by glazec** [comment]
请问你是指谷歌浏览器在**弹窗**询问是否订阅上有问题吗？

**Comment by qingchenmowang** [comment]
就是询问是否订阅不显示，
![image](https://user-images.githubusercontent.com/56811087/80334802-dd6a1900-8884-11ea-9add-83964858a55b.png)

**Comment by qingchenmowang** [comment]
上面这个是谷歌浏览器

**Comment by glazec** [comment]
我这用chrome打开是可以的。
![image](https://user-images.githubusercontent.com/22890026/80334979-c507e900-8807-11ea-9117-370b491cae28.png)

你打不开的原因可能是你在近期拒绝过接受通知。所以弹窗短时间内就不会再出现了。

**Comment by qingchenmowang** [comment]
360极速浏览器显示是否订阅，我选择了订阅，右下小铃铛也出现了
![image](https://user-images.githubusercontent.com/56811087/80334927-48b3eb00-8885-11ea-8d8b-ec5c63a38a35.png)
但是，我点取消订阅就会报错
![image](https://user-images.githubusercontent.com/56811087/80334952-62edc900-8885-11ea-86f6-7343e43ce67f.png)

**Comment by qingchenmowang** [comment]
好的，多谢，那估计就是我谷歌浏览器有问题，我重新安装一遍试试

**Comment by glazec** [comment]
您试一试用隐私模式浏览，看会不会跳弹窗

**Comment by qingchenmowang** [comment]
好的。多谢
