### ISSUE TITLE
Notification badge is not shown

### ISSUE THREAD

**Issue by tienhm0202** [glazec/hexo-web-push-notification#5]
Webpushr can config prompt only. But when I send notification to hexo website, it can not recognize badge and website icon.

**Comment by tienhm0202** [comment]
I found a way to fix this. In JSONFeed, we need to add badge and icon as site favicon URL.

https://developers.google.com/web/fundamentals/push-notifications/display-a-notification

But I don't know how to test plugin

**Comment by glazec** [comment]
Thanks for your contribution. I think these settings in webpushr may help you. If it does not work, please let me konw.
![image](https://user-images.githubusercontent.com/22890026/82109958-77d4b400-96ef-11ea-8468-2836ab8a1b6b.png)

**Comment by tienhm0202** [comment]
@glazec I did these settings in webpushr, but it not working with mobile device

**Comment by glazec** [comment]
Are you having trouble with safari badges for iPhones?

**Comment by tienhm0202** [comment]
I have trouble with Chrome in Android - with Samsung. When notification sent via notification center. 

Bonus: My website have been saved as pwa application. But app icon is still display.

**Comment by glazec** [comment]
Then your problem should be android badges. If there is no problem in the webpushr setting, the problem should be how I call the webpushr API. I think the problem may be solved by putting the icon key in the API call. 

https://docs.webpushr.com/send-push-to-all-subscribers

**Comment by glazec** [comment]
I have duplicated the issue.
![image](https://user-images.githubusercontent.com/22890026/82496074-fb502580-9aa0-11ea-8c0c-e5e0e5cbbefc.png)

**Comment by glazec** [comment]
To fix this issue, you need to use the alpha channel image for badges.
![image](https://user-images.githubusercontent.com/22890026/82496469-a2cd5800-9aa1-11ea-9404-e6baeb17e5c0.png)

![image](https://user-images.githubusercontent.com/22890026/82496542-c8f2f800-9aa1-11ea-9836-0779c6ce8a69.png)

**Comment by tienhm0202** [comment]
Yes, add alpha channel can fix this issues. Thank you so much. I will close this issue.

P/S: For anyone don't know how to create alpha channel: https://www.designeasy.co/2019/09/why-and-how-to-create-alpha-channel-in.html
