### ISSUE TITLE
No New Post detected after deploy

### ISSUE THREAD

**Issue by WardZhouA** [glazec/hexo-web-push-notification#8]
![image](https://user-images.githubusercontent.com/33411000/83345723-16e0e900-a349-11ea-9191-cb8673520e3a.png)
![image](https://user-images.githubusercontent.com/33411000/83345764-5a3b5780-a349-11ea-8a13-07e6584c541b.png)

创建新文章之后，运行过Hexo g && hexo s
然后运行hexo d
并没有触发通知推送

[32mINFO [39m Deploy done: [35mgit[39m
[32mINFO [39m No New Post detected.

好像是在我deploy完成后才检测有没有新文章？

**Comment by glazec** [comment]
对。因为考虑到deploy完成后，网站还需要一段时间build。在build之后，网站才会展现最新的内容。如果您认为是插件触发事件的问题，请做一下改动进行验证。
1. 打开`hexo-root-dir/node_modules/hexo-web-push-notification/index.js`
2. 更改第三十三行为以下代码
```js
hexo.on("deployBefore", async function (post) {
```

**Comment by WardZhouA** [comment]
> 对。因为考虑到deploy完成后，网站还需要一段时间build。在build之后，网站才会展现最新的内容。如果您认为是插件触发时间的问题，请做一下改动进行验证。
> 
> 1. 打开`hexo-root-dir/node_modules/hexo-web-push-notification/index.js`
> 2. 更改第三十三行为以下代码
> 
> ```js
> hexo.on("deployBefore", async function (post) {
> ```

非常感谢，但并非是这个原因造成的，deploy的时候还是会周期性失灵，检测不到新文章

**Comment by glazec** [comment]
目前的检测机制是对比网站上的newPost.json 和本地newPost.json中的id。你可以提供更多的细节吗？比如你是如何发布新文章的，你的网站的build流程

**Comment by WardZhouA** [comment]
> 目前的检测机制是对比网站上的newPost.json 和本地newPost.json中的id。你可以提供更多的细节吗？比如你是如何发布新文章的，你的网站的build流程

目前是通过git推送到github和云主机上（nginx托管），国内访问套了层cdn，我之前有测试过，网站上newPost.json 和本地newPost.json 内容不同，还是会提示no new post detect，有点迷惑，有一定几率在我推送推新文章的时候还能能触发的

**Comment by glazec** [comment]
我也迷惑

**Comment by WardZhouA** [comment]
> 我也迷惑

感谢，如果找到原因我再另开issue

**Comment by glazec** [comment]
> 真的是挺诡异的…..我能收到你网站的通知，自己的收不到，我看后台也是推送成功的….
你可以使用webpushr的segement功能。将自己归为test组。然后给test组的用户推送通知。有可能是你的浏览器因为某些原因没有订阅上。

**Comment by glazec** [comment]
#15
