### ISSUE TITLE
I didn't receive notification after deployment

### ISSUE THREAD

**Issue by small-rose** [glazec/hexo-web-push-notification#9]
follow the step , I didn't receive notification after deployment，I tried several times . that why ? when i send a notification by the API on the official API-playground .

**Comment by glazec** [comment]
请问您可以详细说明一下最后一句吗？您是指再API playground里你成功发送了消息，但是使用插件的时候没有收到消息吗？

**Comment by small-rose** [comment]
是的，我在API playground里手工推送成功发送了消息，也看到推送通知了，但是部署之后没有收到，会不会是因为电脑网络不能直接掉推送API的那个send/all的接口？

**Comment by glazec** [comment]
请问可以提供一下您执行部署后的终端的输出吗？

**Comment by glazec** [comment]
send/all的接口是公共的API接口，是可以使用的。

**Comment by small-rose** [comment]
可以。为了让newPost.json变化，我将之前的一篇文章的日期，修改为今天的日期。

部署之后，最后打印了一句

INFO  No New Post detected.

**Comment by small-rose** [comment]
是不是只修改日期不能判定为新文章？

**Comment by glazec** [comment]
修改日期不会判定为新文章。

**Comment by small-rose** [comment]
今天我新建了一篇全新的文章，部署的时候依旧是：
......
INFO  Deploy done: git
INFO  No New Post detected.

newPost.json文件内容如下：

{"title":"只是为了测试文章推送","id":"posts/6ec5c6dc.html","date_published":"07/04/2020","summary":"你收的道文章吗？","url":"https://www.zhangxiaocai.cn/posts/6ec5c6dc.html","tags":["Test"],"categories":["Test"]}

**Comment by glazec** [comment]
请您尝试打开`hexo-root-dir/node_modules/hexo-web-push-notification/index.js`
更改第三十三行为以下代码
```
hexo.on("deployBefore", async function (post) {

```
如果可以的话打印程序中的 `newPostOnlineSite`和`newPostLocal`两个变量。

**Comment by glazec** [comment]
我的猜测是可能你的网站构建的速度很快。在这个插件运行前便已经更新好了。因此插件认为你的网站已经是最新的了。

**Comment by small-rose** [comment]
这样改了之后部署时有提示报错信息：
-------------------------------------------------------
 (node:8248) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Hexo.<anonymous> (D:\NodeWorks\Hexo-tencent\node_modules\hexo-web-push-notification\index.js:53:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:8248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

------------------------------------------------------

index.js的53行29列，URL为定义，代码如下
-------------------------
target_url: new URL(newPostLocal.url).pathname,
------------------------

**Comment by glazec** [comment]
在我的运行环境中没有任何问题。
```
hexo: 4.2.1
hexo-cli: 3.1.0
os: Windows_NT 10.0.19041 win32 x64
node: 12.14.1
```
第33行到第61行应该长这个样子。
```
hexo.on("deployBefore", async function (post) {
    // Get newPost.json from your site.
    var newPostOnlineSite = await fetch(url.resolve(hexo.config.url, "newPost.json"));
    var newPostOnlineSite = await newPostOnlineSite.json();
    newPostOnlineSite = JSON.parse(JSON.stringify(newPostOnlineSite));
    // Get newPost.json from your local.
    var newPostLocal = await fs.readFileSync('public/newPost.json')
    // Get newPost.json from local
    newPostLocal = JSON.parse(newPostLocal);
    // console.table({
    //     "From online site": newPostOnlineSite,
    //     "From Local": newPostLocal
    // });
    //determine whether to push web notification
    console.log('From your site')
    console.log(newPostOnlineSite)
    console.log('==================')
    console.log('From local')
    console.log(newPostLocal)
    if (newPostOnlineSite.id != newPostLocal.id) {
        // push new Post notification
        var payload = {
            title: newPostLocal.title,
            message: newPostLocal.summary,
            target_url: new URL(newPostLocal.url).pathname,
            // segment: [4205],
            send_at: moment().add(10, 'minutes').format()
            // sid: '4557611'
        };
```

**Comment by glazec** [comment]
注意，即使成功调用api，通知也不会即时显现。通知会在5分钟后出现。

**Comment by small-rose** [comment]
hexo: 4.2.1
hexo-cli: 3.1.0
os: Windows_NT 10.0.18362 win32 x64
node: 8.12.0
------------------------

上面是我的环境，可能就是Node不一样了。


我使用你贴的代码，今天测试了一下，还是这个错误:
----------------------------------------------------------------

INFO  newPostOnlineSite.idposts/ae8510ea.html
INFO  newPostLocal.idposts/a53a9069.html
(node:19372) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Hexo.<anonymous> (D:\NodeWorks\Hexo-tencent\node_modules\hexo-web-push-notification\index.js:56:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:19372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by glazec** [comment]
由于你运行未修改过的插件时没有报错，可能并不是node兼容性的问题。

报错中的URL是从hexo的api中获取的。
